# Generated by Django 6.0.2 on 2026-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
